# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoaHelperIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoaHelperIOS
  pod 'CocoaHelper', :path => '../'
end

target 'CocoaHelperOSX' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoaHelperOSX
  pod 'CocoaHelper', :path => '../'
end
